import { Inter } from 'next/font/google'
import AppLayout from '@/components/layouts/app';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FlightEye',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  )
}
